version: '2'
services:
  wiki:
    image: 'ryu310/pukiwiki-plus:php-7-apache-1.4.7-05'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'wiki_data:/var/www/html'
    # Set if you want to access subdir name instead of root like `http://localhost/wiki/`
#    environment:
#      - SUBDIR=/wiki
    ports:
      - 80:80
    # Enable to restart container (It is useful for Docker for Windows)
#    restart: always
volumes:
  wiki_data:
