version: '2'
services:
  wiki:
    image: 'ryu310/pukiwiki-plus:7-apache-1.4.7-03'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'wiki_data:/var/www/html'
    ports:
      - 80:80
    # Enable to restart container (It is useful for Docker for Windows)
    #restart: always
volumes:
  wiki_data:
